# Generated by Django 5.0.6 on 2024-05-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcommerce', '0002_address_author_genre_remove_book_book_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookcommerce.author'),
        ),
    ]
