# Generated by Django 5.0.6 on 2024-05-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcommerce', '0002_cart_cartitem_cart_books_order_orderitem_order_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookcommerce.cart'),
        ),
    ]
