# Generated by Django 5.0.6 on 2024-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcommerce', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/default_profile_img.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
